### ISSUE TITLE
cloudpickle multiprocessing Pipe

### ISSUE THREAD

**Issue by runflowcode** [cloudpipe/cloudpickle#147]
Hi,

I am curious as to why cloudpickle is having trouble with multiprocessing pipe.

<pre>
import cloudpickle
import multiprocessing
def p_test():
    p = multiprocessing.Pipe()
    pickled = cloudpickle.dumps(p)
    original = cloudpickle.loads(pickled)
    print original
</pre>

>   File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1083, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: Required argument 'handle' (pos 1) not found

**Comment by llllllllll** [comment]
It looks like you've stumbled on a pretty common limitation of pickle. There is no way to pickle a multiprocessing pipe because it depends on an active external resource: the other end of the pipe. cloudpickle is mainly used in a distributed context, where the receiver of an object may be on another machine. In this case, a multiprocessing pipe would be unable to establish communication back to the original machine, so we would not be able to reconstruct this object. This can still be a challenge if you are on the same machine, for example: if I send the the pipe object to another process, it will not have access to the underlying operating system pipe to communicate. Another problem would be if I save the pickled Pipe object to disk and then read it back later. In this case, the process I am trying to communicate with may have already exited or closed the pipe. This is very similar to trying to pickle an open file. If I saved a file object and sent it to another machine, it would not be able to recreate the object because the file may not be available on that new machine. Hopefully this helps explain why cloudpickle (or pickle) cannot save multiprocessing pipes.
