### ISSUE TITLE
cpickle

### ISSUE THREAD

**Issue by rutujar** [cloudpipe/cloudpickle#258]
* how to install cpickle? for ubuntu 16.04
* the part of the code
import pickle
charModel = cPickle.loads(open(args["char_classifier"]).read())
digitModel = cPickle.loads(open(args["digit_classifier"]).read())

* error
    charModel = cPickle.loads(open(args["char_classifier"]).read())
NameError: name 'cPickle' is not defined

how to resolve this issue help needed.

**Comment by pierreglaser** [comment]
`cpickle` and `cloudpickle` are two different things.

* `cPickle` is the `C` accelerated version of the `pickle` module. It is part of the `python` standard library, and exists only on `python 2` (On `python 3`, the `cPickle` module was renamed to `_pickle`).
* `cloudpickle` (the package you just posted the issue on) is a third-party module with functionalities that are not supported by the standard library `pickle` implementation.

This issue concerns `cPickle`, and is unrelated to `cloudpickle`, so it will be closed. Here is why your code is not working though:

Assuming you are using `python2`, the issue is that you did not import `cPickle` before using it, therefore the interpreter complains. instead of importing `pickle` (that is unused in your script), import `cPickle`:

```python
import cPickle
charModel = cPickle.loads(open(args["char_classifier"]).read())
digitModel = cPickle.loads(open(args["digit_classifier"]).read())
```

**Comment by rutujar** [comment]
@pierreglaser Thanks for the help and logic behind it.

Actually it is not working in both python2 and python3.
