### ISSUE TITLE
1.1.1 changelog entries missing from CHANGES.md

### ISSUE THREAD

**Issue by koobs** [cloudpipe/cloudpickle#270]
Understandably and while its a minor PyPI release-only related change, downstream packagers use authoritive links to upstream changelog documents (in this case CHANGES.md) using git tag URL's for that specific version of the document to share with users in their commit log messages.

In this case, https://github.com/cloudpipe/cloudpickle/blob/v1.1.1/CHANGES.md shows changes only up to 1.1.0, which can confuse users, leaving us only with a choice to use a versionless URL, whos content changes all the time, or not include a changelog link, which reduces the user experience and increases the burden on them to locate the changes for themselves

It would be great if the changelog document could include any/all changes, no matter how insignificant, prior to tagging a release and adding a git tag for that version.

Thanks!

**Comment by ogrisel** [comment]
Good point. I will be more careful in the future.

I will push a fix to master but I probably don't want to update the existing 1.1.1 tag.

**Comment by ogrisel** [comment]
Fixed in 61761935ff0b101784534747679ce88a1c9d617a.

You can use https://github.com/cloudpipe/cloudpickle/blob/master/CHANGES.md#111 as a version dependent URL. Or even https://github.com/cloudpipe/cloudpickle/blob/61761935ff0b101784534747679ce88a1c9d617a/CHANGES.md#111 to make it immutable.

Sorry for the inconvenience @koobs.

**Comment by koobs** [comment]
No need for apologies, much appreciated @ogrisel! :)
