### ISSUE TITLE
Parallelize serialization

### ISSUE THREAD

**Issue by basnijholt** [cloudpipe/cloudpickle#374]
In [Adaptive-scheduler](https://adaptive-scheduler.readthedocs.io/) (package to run adaptive parameter sweeps on >30.000 cores) serialization takes most of the time (sending the functions (+known data) to run to the compute nodes). In [adaptive-scheduler PR #44](https://github.com/basnijholt/adaptive-scheduler/pull/44/files#diff-5e241bdb2d5e8ca5eafc63f0eaef28caR534) I am trying to have the serialization happen in threads, however, I am not observing any speedup.

I can reproduce this with the following code
```python
%%time
import itertools
import cloudpickle
from concurrent.futures import ThreadPoolExecutor

x = np.random.rand(10000, 10000)
# y = cloudpickle.dumps(x)  # <---------------- takes 1.5s
with ThreadPoolExecutor() as ex:
    ex.map(cloudpickle.dumps, itertools.repeat(x, 10))
```
which takes 8s.

Is this because of the GIL?

Using a `ProcessPoolExecutor` also doesn't result in any speedup.

Is there a way in which I can call `cloudpickle.dumps` on different objects in parallel efficiently?

**Comment by ogrisel** [comment]
> Is this because of the GIL?

Yes (because cloudpickle can manipulate many small Python objects so it's not possible to release the GIL in those cases) + the fact that pickling is probably not very CPU intensive (compared to the cost of memory access) especially in the numpy-based example you give in the description of this issue.

> Using a ProcessPoolExecutor also doesn't result in any speedup.

This is expected because to communicate with the worker proceses, the data needs to be both pickled and unpickled even before calling your function in the worke process.

> Is there a way in which I can call cloudpickle.dumps on different objects in parallel efficiently?

I don't see any.
