### ISSUE TITLE
can't pickle dict_keys objects

### ISSUE THREAD

**Issue by brl0** [cloudpipe/cloudpickle#380]
Using Dask.distributed, which uses cloudpickle for serialization, I encounter an error when passing a `dict_keys` object as a parameter to a function.  I reported the issue [there](https://github.com/dask/distributed/issues/3893), where it was suggested that I also report an issue here for consideration.

As a test, I attempted to use cloudpickle directly on this type of object and received the following error: 
`TypeError: can't pickle dict_keys objects`

Would it be possible to add the ability to pickle `dict_keys` object?

**Comment by ogrisel** [comment]
I wonder why this is not the case by default in Python though:

```python
>>> import pickle                                                                                  
>>> pickle.dumps({}.keys())                                                                        
Traceback (most recent call last):
  File "<ipython-input-6-6d75fd452bb1>", line 1, in <module>
    pickle.dumps({}.keys())
TypeError: cannot pickle 'dict_keys' object
```

Maybe I miss something. Maybe because unsuspecting users would risk sending the dict values as part of the pickle without realizing it?

I suppose we could write a reducer in cloudpickle that would ship the whole dict (which should be picklable) and reconstruct the `dict_keys` view on the other side. Same for dict values and items.

Would you be interested in contributing a PR?

**Comment by brl0** [comment]
Thanks for your response.  

I would be interested in attempting to contribute, but after taking a look at the codebase, I am honestly not sure where/how to start.  I am open to guidance if you are willing to point me in the right direction.

My initial thought is that it would be best not to ship the whole dict, because it could be large, complex, or contain sensitive information that is not needed.
